using System.Collections.Generic;
using CustomRecipes.ScalingParams;
using ReLogic.Content;
using ReLogic.Graphics;
using Terraria.Audio;
using Terraria.ID;
using Terraria.ModLoader;

namespace CustomRecipes;

// Please read https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Modding-Guide#mod-skeleton-contents for more information about the various files in a mod.
// ReSharper disable once ClassNeverInstantiated.Global
public class CustomRecipes : Mod
{
    public static DynamicSpriteFont OptimusPrincepsFont;
    public static SoundStyle DsNewAreaSound;
    public static SoundStyle DsThruDeath;
    public static SoundStyle DsSoulSuck;
    
    private const string AssetsPath = "CustomRecipes/Assets";

    public override void Load()
    {
        base.Load();

        OptimusPrincepsFont = ModContent
            .Request<DynamicSpriteFont>($"{AssetsPath}/Fonts/OptimusPrinceps", AssetRequestMode.ImmediateLoad)
            .Value;

        DsNewAreaSound = new SoundStyle($"{AssetsPath}/Sounds/DS_NewArea") { Volume = 0.35f };
        DsThruDeath = new SoundStyle($"{AssetsPath}/Sounds/DS_ThruDeath") { Volume = 0.7f };
        DsSoulSuck = new SoundStyle($"{AssetsPath}/Sounds/DS_SoulSuckBonus") { Volume = 0.4f, PitchVariance = 0.2f };
    }

    public override void Unload()
    {
        base.Unload();

        OptimusPrincepsFont = null;

        DsNewAreaSound = default;
        DsThruDeath = default;
        DsSoulSuck = default;
    }

    public static readonly Dictionary<int, WeaponParams> AllWeaponsParams = new()
    {
        { ItemID.AbigailsFlower, new WeaponParams() },

        { ItemID.AdamantiteChainsaw, new WeaponParams(14, 10) },
        { ItemID.AdamantiteDrill, new WeaponParams(8) },
        { ItemID.AdamantiteGlaive, new WeaponParams(15, 10, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.AdamantitePickaxe, new WeaponParams(8) },
        { ItemID.AdamantiteRepeater, new WeaponParams(8, 16, dexScalingGrade: ScalingGrade.D) },
        { ItemID.AdamantiteSword, new WeaponParams(16, 10, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.AdamantiteWaraxe, new WeaponParams(21, 6, 0, 0, ScalingGrade.C, ScalingGrade.E) },

        { ItemID.TitaniumChainsaw, new WeaponParams(14, 10) },
        { ItemID.TitaniumDrill, new WeaponParams(8) },
        { ItemID.TitaniumTrident, new WeaponParams(15, 10, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.TitaniumPickaxe, new WeaponParams(8) },
        { ItemID.TitaniumRepeater, new WeaponParams(8, 16, dexScalingGrade: ScalingGrade.D) },
        { ItemID.TitaniumSword, new WeaponParams(16, 10, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.TitaniumWaraxe, new WeaponParams(21, 6, 0, 0, ScalingGrade.C, ScalingGrade.E) },

        { ItemID.DD2BetsyBow, new WeaponParams(8, 30, 0, 0, ScalingGrade.E, ScalingGrade.B) },
        { ItemID.AleThrowingGlove, new WeaponParams(8, 12, 0, 0, ScalingGrade.E, ScalingGrade.C) },
        { ItemID.Amarok, new WeaponParams(12, 12, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.JungleYoyo, new WeaponParams(5, 5, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.AmberStaff, new WeaponParams(2, 2, 5, 1, ScalingGrade.None, ScalingGrade.None, ScalingGrade.D) },
        { ItemID.AmethystStaff, new WeaponParams(2, 2, 5, 1, ScalingGrade.None, ScalingGrade.None, ScalingGrade.D) },
        { ItemID.Anchor, new WeaponParams(25, 5, 0, 0, ScalingGrade.B) },
        { ItemID.AquaScepter, new WeaponParams(2, 2, 12, 0, ScalingGrade.None, ScalingGrade.None, ScalingGrade.D) },
        { ItemID.Arkhalis, new WeaponParams(8, 12, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.CrimsonYoyo, new WeaponParams(6, 6, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.AshWoodBow, new WeaponParams() },
        { ItemID.AshWoodHammer, new WeaponParams() },
        { ItemID.AshWoodSword, new WeaponParams() },
        { ItemID.AcornAxe, new WeaponParams(3, 5) },
        { ItemID.BallOHurt, new WeaponParams(8, 5, 0, 0, ScalingGrade.E) },
        { ItemID.DD2BallistraTowerT1Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2BallistraTowerT2Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2BallistraTowerT3Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.Bananarang, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.BatBat, new WeaponParams(18, 5, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.BatScepter, new WeaponParams(3, 3, 22, 5, intScalingGrade: ScalingGrade.C, faiScalingGrade: ScalingGrade.E) },
        { ItemID.BeamSword, new WeaponParams(15, 5, 5, 0, ScalingGrade.C, ScalingGrade.None, ScalingGrade.E) },
        { ItemID.BeeGun, new WeaponParams(3, 2, 12, intScalingGrade: ScalingGrade.D) },
        { ItemID.BeeKeeper, new WeaponParams(10, 5, 0, 0, ScalingGrade.D) },
        { ItemID.Beenade, new WeaponParams(5, 8, 0, 0, ScalingGrade.None, ScalingGrade.A) },
        { ItemID.ApprenticeStaffT3, new WeaponParams(5, 3, 37, intScalingGrade: ScalingGrade.B) },
        { ItemID.BladeofGrass, new WeaponParams(8, 5, 0, 0, ScalingGrade.D) },
        { ItemID.Smolstar, new WeaponParams(1, 1, 3, 15, faiScalingGrade: ScalingGrade.C) },
        { ItemID.BladedGlove, new WeaponParams(5, 12, 0, 0, ScalingGrade.E, ScalingGrade.D) },
        { ItemID.Bladetongue, new WeaponParams(12, 5, 5, 0, ScalingGrade.D, ScalingGrade.None, ScalingGrade.E) },
        { ItemID.BlizzardStaff, new WeaponParams(2, 2, 36, intScalingGrade: ScalingGrade.B) },
        { ItemID.BloodButcherer, new WeaponParams(10, 2, 0, 0, ScalingGrade.D) },
        { ItemID.BloodLustCluster, new WeaponParams(10, 2, 0, 0, ScalingGrade.D) },
        { ItemID.BloodRainBow, new WeaponParams(2, 10, dexScalingGrade: ScalingGrade.D) },
        { ItemID.SharpTears, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.BloodWater, new WeaponParams() },
        { ItemID.BloodyMachete, new WeaponParams(6, 6, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.Blowgun, new WeaponParams(2, 12, dexScalingGrade: ScalingGrade.D) },
        { ItemID.Blowpipe, new WeaponParams(2, 3, dexScalingGrade: ScalingGrade.E) },
        { ItemID.BlueMoon, new WeaponParams(12, 5, 0, 0, ScalingGrade.D) },

        { ItemID.BluePhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.GreenPhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.OrangePhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.PurplePhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.RedPhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.WhitePhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.YellowPhaseblade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },

        { ItemID.BluePhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.C) },
        { ItemID.GreenPhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.C) },
        { ItemID.OrangePhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.C) },
        { ItemID.PurplePhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.C) },
        { ItemID.RedPhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.C) },
        { ItemID.WhitePhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.B) },
        { ItemID.YellowPhasesaber, new WeaponParams(12, 12, 0, 0, ScalingGrade.D, ScalingGrade.C) },

        { ItemID.BlueRocket, new WeaponParams(0, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.GreenRocket, new WeaponParams(0, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.RedRocket, new WeaponParams(0, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.YellowRocket, new WeaponParams(0, 5, dexScalingGrade: ScalingGrade.S) },

        { ItemID.Bomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.BombFish, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.Bone, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.BoneJavelin, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.BonePickaxe, new WeaponParams(3) },
        { ItemID.BoneSword, new WeaponParams(8, 2, 0, 0, ScalingGrade.E) },
        { ItemID.BoneDagger, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.C) },
        { ItemID.BookofSkulls, new WeaponParams(2, 2, 13, intScalingGrade: ScalingGrade.D) },
        { ItemID.Boomstick, new WeaponParams(2, 8, dexScalingGrade: ScalingGrade.D) },
        { ItemID.BorealWoodBow, new WeaponParams() },
        { ItemID.BorealWoodHammer, new WeaponParams() },
        { ItemID.BorealWoodSword, new WeaponParams() },
        { ItemID.BouncyBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.BouncyDynamite, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.BouncyGrenade, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.DD2SquireDemonSword, new WeaponParams(30, 8, 0, 0, ScalingGrade.C) },
        { ItemID.BreakerBlade, new WeaponParams(20, 5, 0, 0, ScalingGrade.B) },
        { ItemID.BreathingReed, new WeaponParams(3, 3) },
        { ItemID.BubbleGun, new WeaponParams(2, 2, 32, intScalingGrade: ScalingGrade.B) },
        { ItemID.BunnyCannon, new WeaponParams() },
        { ItemID.ButchersChainsaw, new WeaponParams(20, 15, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.CactusPickaxe, new WeaponParams() },
        { ItemID.CactusSword, new WeaponParams(3, 1) },
        { ItemID.CnadyCanePickaxe, new WeaponParams(3) },
        { ItemID.CandyCaneSword, new WeaponParams(8, 2, 0, 0, ScalingGrade.E) },
        { ItemID.CandyCornRifle, new WeaponParams(6, 25, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Cannon, new WeaponParams() },
        { ItemID.Cascade, new WeaponParams(8, 8, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.FireworksLauncher, new WeaponParams(5, 25, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Celeb2, new WeaponParams(10, 40, dexScalingGrade: ScalingGrade.A) },
        { ItemID.ChainGuillotines, new WeaponParams(20, 5, 0, 0, ScalingGrade.C) },
        { ItemID.ChainGun, new WeaponParams(8, 32, dexScalingGrade: ScalingGrade.C) },
        { ItemID.ChainKnife, new WeaponParams(6, 5, 0, 0, ScalingGrade.D) },
        { ItemID.ChargedBlasterCannon, new WeaponParams(3, 3, 35, intScalingGrade: ScalingGrade.B) },
        { ItemID.Chik, new WeaponParams(12, 12, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.ChlorophyteChainsaw, new WeaponParams(18, 8, 0, 0, ScalingGrade.C) },
        { ItemID.ChlorophyteClaymore, new WeaponParams(22, 5, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.ChlorophyteDrill, new WeaponParams(9) },
        { ItemID.ChlorophyteGreataxe, new WeaponParams(25, 5, 0, 0, ScalingGrade.B, ScalingGrade.E) },
        { ItemID.ChlorophyteJackhammer, new WeaponParams(15, 12) },
        { ItemID.ChlorophytePartisan, new WeaponParams(20, 10, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.ChlorophyteSaber, new WeaponParams(20, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.ChlorophyteShotbow, new WeaponParams(5, 26, dexScalingGrade: ScalingGrade.C) },
        { ItemID.ChlorophyteWarhammer, new WeaponParams(28, 5, 0, 0, ScalingGrade.A, ScalingGrade.E) },
        { ItemID.ChlorophytePickaxe, new WeaponParams(9) },

        { ItemID.ChristmasTreeSword, new WeaponParams(25, 8, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.TaxCollectorsStickOfDoom, new WeaponParams(6, 6, 0, 0, ScalingGrade.B, ScalingGrade.B) },
        { ItemID.ClingerStaff, new WeaponParams(3, 2, 25, intScalingGrade: ScalingGrade.C) },
        { ItemID.ClockworkAssaultRifle, new WeaponParams(5, 15, dexScalingGrade: ScalingGrade.C) },

        { ItemID.CobaltChainsaw, new WeaponParams(12, 8) },
        { ItemID.CobaltDrill, new WeaponParams(6) },
        { ItemID.CobaltNaginata, new WeaponParams(12, 8, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.CobaltPickaxe, new WeaponParams(6) },
        { ItemID.CobaltRepeater, new WeaponParams(8, 12, dexScalingGrade: ScalingGrade.D) },
        { ItemID.CobaltSword, new WeaponParams(15, 5, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.CobaltWaraxe, new WeaponParams(18, 4, 0, 0, ScalingGrade.D, ScalingGrade.E) },

        { ItemID.PalladiumChainsaw, new WeaponParams(12, 8) },
        { ItemID.PalladiumDrill, new WeaponParams(6) },
        { ItemID.PalladiumPike, new WeaponParams(12, 8, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.PalladiumPickaxe, new WeaponParams(6) },
        { ItemID.PalladiumRepeater, new WeaponParams(8, 12, dexScalingGrade: ScalingGrade.D) },
        { ItemID.PalladiumSword, new WeaponParams(15, 5, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.PalladiumWaraxe, new WeaponParams(18, 4, 0, 0, ScalingGrade.D, ScalingGrade.E) },

        { ItemID.Code1, new WeaponParams(10, 10, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.Code2, new WeaponParams(14, 14, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.CoinGun, new WeaponParams(5, 20) },
        { ItemID.CombatWrench, new WeaponParams(8, 8, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.CoolWhip, new WeaponParams(2, 3, 0, 18, faiScalingGrade: ScalingGrade.C) },
        { ItemID.CopperAxe, new WeaponParams() },
        { ItemID.CopperBow, new WeaponParams() },
        { ItemID.CopperBroadsword, new WeaponParams() },
        { ItemID.CopperHammer, new WeaponParams() },
        { ItemID.CopperPickaxe, new WeaponParams() },
        { ItemID.CopperShortsword, new WeaponParams() },
        { ItemID.CrimsonRod, new WeaponParams(1, 1, 10, intScalingGrade: ScalingGrade.E) },
        { ItemID.CrystalSerpent, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.CrystalStorm, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.CrystalVileShard, new WeaponParams(2, 2, 14, intScalingGrade: ScalingGrade.D) },
        { ItemID.CursedFlames, new WeaponParams(2, 2, 20, intScalingGrade: ScalingGrade.D) },
        { ItemID.Cutlass, new WeaponParams(16, 8, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.DaedalusStormbow, new WeaponParams(4, 21, dexScalingGrade: ScalingGrade.C) },
        { ItemID.DaoofPow, new WeaponParams(20, 5, 0, 0, ScalingGrade.C) },
        { ItemID.ScytheWhip, new WeaponParams(2, 4, 0, 30, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DarkLance, new WeaponParams(12, 5, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.DartPistol, new WeaponParams(5, 15, dexScalingGrade: ScalingGrade.D) },
        { ItemID.DartRifle, new WeaponParams(5, 15, dexScalingGrade: ScalingGrade.D) },
        { ItemID.DeadlySphereStaff, new WeaponParams(2, 2, 0, 35, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DeathSickle, new WeaponParams(26, 8, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.DeathbringerPickaxe, new WeaponParams(4) },
        { ItemID.DemonBow, new WeaponParams(4, 8, dexScalingGrade: ScalingGrade.E) },
        { ItemID.DemonScythe, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.StormTigerStaff, new WeaponParams(2, 2, 0, 36, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DiamondStaff, new WeaponParams(2, 2, 6, intScalingGrade: ScalingGrade.D) },
        { ItemID.DirtBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.Drax, new WeaponParams(9) },
        { ItemID.DripplerFlail, new WeaponParams(15, 3, 0, 0, ScalingGrade.C) },
        { ItemID.DryBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.SwordWhip, new WeaponParams(2, 3, 0, 24, faiScalingGrade: ScalingGrade.C) },
        { ItemID.Dynamite, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.EbonwoodBow, new WeaponParams() },
        { ItemID.EbonwoodHammer, new WeaponParams() },
        { ItemID.EbonwoodSword, new WeaponParams() },
        { ItemID.ElectrosphereLauncher, new WeaponParams(2, 32, dexScalingGrade: ScalingGrade.C) },
        { ItemID.ElfMelter, new WeaponParams(2, 32, dexScalingGrade: ScalingGrade.C) },
        { ItemID.EmeraldStaff, new WeaponParams(2, 2, 6, intScalingGrade: ScalingGrade.E) },
        { ItemID.EnchantedBoomerang, new WeaponParams(5, 5, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.EnchantedSword, new WeaponParams(7, 2, 2, 0, ScalingGrade.D, ScalingGrade.None, ScalingGrade.E) },
        { ItemID.FairyQueenRangedItem, new WeaponParams(2, 30, dexScalingGrade: ScalingGrade.B) },
        { ItemID.Excalibur, new WeaponParams(20, 8, 0, 0, ScalingGrade.B, ScalingGrade.E) },
        { ItemID.DyeTradersScimitar, new WeaponParams(10, 4, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.DD2ExplosiveTrapT1Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2ExplosiveTrapT2Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2ExplosiveTrapT3Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.FalconBlade, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.FetidBaghnakhs, new WeaponParams(15, 10, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.BabyBirdStaff, new WeaponParams() },
        { ItemID.FireWhip, new WeaponParams(2, 3, 0, 15, faiScalingGrade: ScalingGrade.D) },
        { ItemID.Flairon, new WeaponParams(28, 4, 0, 0, ScalingGrade.B, ScalingGrade.E) },
        { ItemID.Flamarang, new WeaponParams(10, 10, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.DD2FlameburstTowerT1Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2FlameburstTowerT2Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2FlameburstTowerT3Popper, new WeaponParams(0, 0, 8, 15, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.Flamelash, new WeaponParams(2, 2, 18, intScalingGrade: ScalingGrade.D) },
        { ItemID.Flamethrower, new WeaponParams(2, 22, dexScalingGrade: ScalingGrade.D) },
        { ItemID.FlamingMace, new WeaponParams(10, 5, 0, 0, ScalingGrade.D) },
        { ItemID.FlareGun, new WeaponParams(2, 10, dexScalingGrade: ScalingGrade.A) },
        { ItemID.FleshGrinder, new WeaponParams(12, 3, 0, 0, ScalingGrade.C) },
        { ItemID.FlintlockPistol, new WeaponParams(2, 8, dexScalingGrade: ScalingGrade.D) },
        { ItemID.FlinxStaff, new WeaponParams(1, 1, 0, 6, faiScalingGrade: ScalingGrade.E) },
        { ItemID.FlowerofFire, new WeaponParams(2, 2, 14, intScalingGrade: ScalingGrade.D) },
        { ItemID.FlowerofFrost, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.FlowerPow, new WeaponParams(28, 5, 0, 0, ScalingGrade.B) },
        { ItemID.DD2SquireBetsySword, new WeaponParams(30, 6, 0, 0, ScalingGrade.B) },
        { ItemID.FlyingKnife, new WeaponParams(18, 5, 0, 0, ScalingGrade.D) },
        { ItemID.Flymeal, new WeaponParams(8, 5, 0, 0, ScalingGrade.E) },
        { ItemID.FormatC, new WeaponParams(11, 11, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.FossilPickaxe, new WeaponParams(3) },
        { ItemID.FrostDaggerfish, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.FrostStaff, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.Frostbrand, new WeaponParams(10, 4, 6, 0, ScalingGrade.D, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.FruitcakeChakram, new WeaponParams(6, 6, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.Gatligator, new WeaponParams(3, 15, 0, 0, ScalingGrade.None, ScalingGrade.C) },
        { ItemID.MonkStaffT2, new WeaponParams(16, 12, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.Gladius, new WeaponParams(8, 6, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.GoldAxe, new WeaponParams(5, 4) },
        { ItemID.GoldBow, new WeaponParams(4, 6, dexScalingGrade: ScalingGrade.E) },
        { ItemID.GoldBroadsword, new WeaponParams(8, 2, 0, 0, ScalingGrade.E) },
        { ItemID.GoldHammer, new WeaponParams(9, 2, 0, 0, ScalingGrade.D) },
        { ItemID.GoldPickaxe, new WeaponParams(3) },
        { ItemID.GoldenShower, new WeaponParams(2, 2, 15, intScalingGrade: ScalingGrade.D) },
        { ItemID.GolemFist, new WeaponParams(30, 2, 0, 0, ScalingGrade.A) },
        { ItemID.Gradient, new WeaponParams(13, 13, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.GravediggerShovel, new WeaponParams(2, 6, dexScalingGrade: ScalingGrade.D) },
        { ItemID.ZapinatorGray, new WeaponParams(2, 2, 14, intScalingGrade: ScalingGrade.D) },
        { ItemID.Grenade, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.GrenadeLauncher, new WeaponParams(2, 26, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Gungnir, new WeaponParams(16, 12, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.BloodHamaxe, new WeaponParams(16, 4, 0, 0, ScalingGrade.B) },
        { ItemID.HallowJoustingLance, new WeaponParams(30, 5, 0, 0, ScalingGrade.S) },
        { ItemID.HallowedRepeater, new WeaponParams(10, 18, dexScalingGrade: ScalingGrade.C) },
        { ItemID.HamBat, new WeaponParams(25, 5, 0, 0, ScalingGrade.A) },
        { ItemID.Hammush, new WeaponParams(20, 3, 0, 0, ScalingGrade.C) },
        { ItemID.Handgun, new WeaponParams(3, 12, dexScalingGrade: ScalingGrade.D) },
        { ItemID.PartyGirlGrenade, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.Harpoon, new WeaponParams(2, 13, dexScalingGrade: ScalingGrade.D) },
        { ItemID.HeatRay, new WeaponParams(1, 1, 30, intScalingGrade: ScalingGrade.C) },
        { ItemID.HelFire, new WeaponParams(11, 11, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.HellwingBow, new WeaponParams(2, 12, dexScalingGrade: ScalingGrade.D) },
        { ItemID.HiveFive, new WeaponParams(7, 7, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.HolyWater, new WeaponParams() },
        { ItemID.HoneyBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.HornetStaff, new WeaponParams(2, 2, 0, 8, faiScalingGrade: ScalingGrade.D) },
        { ItemID.HoundiusShootius, new WeaponParams(2, 2, 0, 10, faiScalingGrade: ScalingGrade.D) },
        { ItemID.IceBlade, new WeaponParams(6, 2, 2, 0, ScalingGrade.E, ScalingGrade.None, ScalingGrade.E) },
        { ItemID.IceBoomerang, new WeaponParams(6, 6, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.IceBow, new WeaponParams(4, 16, dexScalingGrade: ScalingGrade.D) },
        { ItemID.IceRod, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.D) },
        { ItemID.IceSickle, new WeaponParams(15, 5, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.ImpStaff, new WeaponParams(2, 2, 0, 13, faiScalingGrade: ScalingGrade.D) },
        { ItemID.InfernoFork, new WeaponParams(2, 2, 32, intScalingGrade: ScalingGrade.D) },
        { ItemID.InfluxWaver, new WeaponParams(26, 10, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.IronAxe, new WeaponParams() },
        { ItemID.IronBow, new WeaponParams() },
        { ItemID.IronBroadsword, new WeaponParams() },
        { ItemID.IronHammer, new WeaponParams() },
        { ItemID.IronPickaxe, new WeaponParams() },
        { ItemID.IronShortsword, new WeaponParams() },
        { ItemID.JackOLanternLauncher, new WeaponParams(5, 30, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Javelin, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.JoustingLance, new WeaponParams(20, 5, 0, 0, ScalingGrade.S) },
        { ItemID.RainbowWhip, new WeaponParams(2, 6, 0, 36, faiScalingGrade: ScalingGrade.A) },
        { ItemID.Katana, new WeaponParams(8, 2, 0, 0, ScalingGrade.E) },
        { ItemID.Keybrand, new WeaponParams(28, 6, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.KOCannon, new WeaponParams(18, 5, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.Kraken, new WeaponParams(18, 18, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.LandMine, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.LaserDrill, new WeaponParams(11) },
        { ItemID.LaserMachinegun, new WeaponParams(4, 2, 32, intScalingGrade: ScalingGrade.B) },
        { ItemID.LaserRifle, new WeaponParams(2, 2, 16, intScalingGrade: ScalingGrade.C) },
        { ItemID.LastPrism, new WeaponParams(2, 2, 50, intScalingGrade: ScalingGrade.A) },
        { ItemID.LavaBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.LeadBow, new WeaponParams() },
        { ItemID.LeadBroadsword, new WeaponParams() },
        { ItemID.LeadHammer, new WeaponParams() },
        { ItemID.LeadPickaxe, new WeaponParams() },
        { ItemID.LeadShortsword, new WeaponParams() },
        { ItemID.LeafBlower, new WeaponParams(1, 1, 30, intScalingGrade: ScalingGrade.C) },
        { ItemID.BlandWhip, new WeaponParams(1, 1, 0, 3, faiScalingGrade: ScalingGrade.D) },
        { ItemID.SoulDrain, new WeaponParams(1, 1, 22, intScalingGrade: ScalingGrade.C) },
        { ItemID.LightDisc, new WeaponParams(14, 14, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.LightsBane, new WeaponParams(10, 2, 0, 0, ScalingGrade.D) },
        { ItemID.DD2LightningAuraT1Popper, new WeaponParams(0, 0, 6, 12, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2LightningAuraT2Popper, new WeaponParams(0, 0, 6, 12, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.DD2LightningAuraT3Popper, new WeaponParams(0, 0, 6, 12, intScalingGrade: ScalingGrade.E, faiScalingGrade: ScalingGrade.C) },
        { ItemID.LucyTheAxe, new WeaponParams(12, 2, 0, 0, ScalingGrade.D) },
        { ItemID.LunarFlareBook, new WeaponParams(2, 2, 50, intScalingGrade: ScalingGrade.A) },
        { ItemID.MoonlordTurretStaff, new WeaponParams(2, 2, 0, 45, faiScalingGrade: ScalingGrade.A) },
        { ItemID.Mace, new WeaponParams(8, 4, 0, 0, ScalingGrade.D) },
        { ItemID.MagicDagger, new WeaponParams(2, 2, 18, intScalingGrade: ScalingGrade.C) },
        { ItemID.MagicMissile, new WeaponParams(2, 2, 12, intScalingGrade: ScalingGrade.D) },
        { ItemID.MagicalHarp, new WeaponParams(2, 2, 18, intScalingGrade: ScalingGrade.C) },
        { ItemID.MagnetSphere, new WeaponParams(2, 2, 30, intScalingGrade: ScalingGrade.C) },
        { ItemID.CorruptYoyo, new WeaponParams(6, 6, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.AntlionClaw, new WeaponParams(8, 4, 0, 0, ScalingGrade.E) },
        { ItemID.Marrow, new WeaponParams(4, 20, dexScalingGrade: ScalingGrade.C) },
        { ItemID.MedusaHead, new WeaponParams(1, 1, 20, intScalingGrade: ScalingGrade.D) },
        { ItemID.Megashark, new WeaponParams(3, 21, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Meowmere, new WeaponParams(40, 10, 0, 0, ScalingGrade.A, ScalingGrade.D) },
        { ItemID.MeteorHamaxe, new WeaponParams(12, 3, 0, 0, ScalingGrade.D) },
        { ItemID.MeteorStaff, new WeaponParams(2, 2, 21, intScalingGrade: ScalingGrade.C) },
        { ItemID.Minishark, new WeaponParams(2, 10, dexScalingGrade: ScalingGrade.D) },
        { ItemID.MolotovCocktail, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.MoltenFury, new WeaponParams(2, 14, dexScalingGrade: ScalingGrade.D) },
        { ItemID.MoltenHamaxe, new WeaponParams(14, 2, 0, 0, ScalingGrade.C) },
        { ItemID.MoltenPickaxe, new WeaponParams(5) },
        { ItemID.MaceWhip, new WeaponParams(2, 5, 0, 32, faiScalingGrade: ScalingGrade.B) },
        { ItemID.Muramasa, new WeaponParams(8, 6, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.MushroomSpear, new WeaponParams(15, 8, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.Musket, new WeaponParams(2, 12, dexScalingGrade: ScalingGrade.C) },

        { ItemID.MythrilChainsaw, new WeaponParams(14, 8) },
        { ItemID.MythrilDrill, new WeaponParams(7) },
        { ItemID.MythrilHalberd, new WeaponParams(12, 10, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.MythrilPickaxe, new WeaponParams(7) },
        { ItemID.MythrilRepeater, new WeaponParams(6, 15, dexScalingGrade: ScalingGrade.D) },
        { ItemID.MythrilSword, new WeaponParams(18, 5, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.MythrilWaraxe, new WeaponParams(20, 5, 0, 0, ScalingGrade.C, ScalingGrade.E) },

        { ItemID.OrichalcumChainsaw, new WeaponParams(14, 8) },
        { ItemID.OrichalcumDrill, new WeaponParams(7) },
        { ItemID.OrichalcumHalberd, new WeaponParams(12, 10, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.OrichalcumPickaxe, new WeaponParams(7) },
        { ItemID.OrichalcumRepeater, new WeaponParams(6, 15, dexScalingGrade: ScalingGrade.D) },
        { ItemID.OrichalcumSword, new WeaponParams(18, 5, 0, 0, ScalingGrade.C, ScalingGrade.E) },
        { ItemID.OrichalcumWaraxe, new WeaponParams(20, 5, 0, 0, ScalingGrade.C, ScalingGrade.E) },

        { ItemID.NailGun, new WeaponParams(6, 27, dexScalingGrade: ScalingGrade.C) },

        { ItemID.NebulaArcanum, new WeaponParams(2, 2, 40, intScalingGrade: ScalingGrade.A) },
        { ItemID.NebulaBlaze, new WeaponParams(2, 2, 42, intScalingGrade: ScalingGrade.B) },
        { ItemID.NebulaDrill, new WeaponParams(11) },
        { ItemID.NebulaPickaxe, new WeaponParams(11) },

        { ItemID.DayBreak, new WeaponParams(40, 5, 0, 0, ScalingGrade.A) },
        { ItemID.SolarEruption, new WeaponParams(40, 5, 0, 0, ScalingGrade.A) },
        { ItemID.SolarFlareDrill, new WeaponParams(11) },
        { ItemID.SolarFlarePickaxe, new WeaponParams(11) },

        { ItemID.VortexBeater, new WeaponParams(5, 40, dexScalingGrade: ScalingGrade.A) },
        { ItemID.Phantasm, new WeaponParams(5, 40, dexScalingGrade: ScalingGrade.A) },
        { ItemID.VortexDrill, new WeaponParams(11) },
        { ItemID.VortexPickaxe, new WeaponParams(11) },

        { ItemID.StardustCellStaff, new WeaponParams(3, 2, 0, 40, faiScalingGrade: ScalingGrade.A) },
        { ItemID.StardustDragonStaff, new WeaponParams(3, 2, 0, 40, faiScalingGrade: ScalingGrade.A) },
        { ItemID.StardustDrill, new WeaponParams(11) },
        { ItemID.StardustPickaxe, new WeaponParams(11) },

        { ItemID.NettleBurst, new WeaponParams(2, 2, 30, intScalingGrade: ScalingGrade.C) },
        { ItemID.NightsEdge, new WeaponParams(13, 5, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.FairyQueenMagicItem, new WeaponParams(2, 2, 35, intScalingGrade: ScalingGrade.A) },
        { ItemID.NightmarePickaxe, new WeaponParams(4) },
        { ItemID.NimbusRod, new WeaponParams(1, 1, 14, intScalingGrade: ScalingGrade.D) },
        { ItemID.NorthPole, new WeaponParams(2, 2, 34, intScalingGrade: ScalingGrade.B) },
        { ItemID.ObsidianSwordfish, new WeaponParams(22, 5, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.OnyxBlaster, new WeaponParams(6, 14, dexScalingGrade: ScalingGrade.C) },
        { ItemID.OpticStaff, new WeaponParams(2, 2, 0, 20, dexScalingGrade: ScalingGrade.C) },
        { ItemID.ZapinatorOrange, new WeaponParams(2, 2, 18, intScalingGrade: ScalingGrade.C) },
        { ItemID.PainterPaintballGun, new WeaponParams(2, 8, dexScalingGrade: ScalingGrade.D) },
        { ItemID.PaladinsHammer, new WeaponParams(30, 5, 0, 0, ScalingGrade.A, ScalingGrade.E) },
        { ItemID.PalmWoodBow, new WeaponParams() },
        { ItemID.PalmWoodHammer, new WeaponParams() },
        { ItemID.PalmWoodSword, new WeaponParams() },
        { ItemID.PaperAirplaneA, new WeaponParams(0, 3, dexScalingGrade: ScalingGrade.S) },
        { ItemID.PaperAirplaneB, new WeaponParams(0, 3, dexScalingGrade: ScalingGrade.S) },
        { ItemID.PearlwoodBow, new WeaponParams() },
        { ItemID.PearlwoodHammer, new WeaponParams() },
        { ItemID.PewMaticHorn, new WeaponParams(2, 8, dexScalingGrade: ScalingGrade.C) },
        { ItemID.DD2PhoenixBow, new WeaponParams(3, 22, dexScalingGrade: ScalingGrade.B) },
        { ItemID.PhoenixBlaster, new WeaponParams(3, 14, dexScalingGrade: ScalingGrade.C) },
        { ItemID.PickaxeAxe, new WeaponParams(9) },
        { ItemID.Picksaw, new WeaponParams(10) },
        { ItemID.PiranhaGun, new WeaponParams(4, 26, dexScalingGrade: ScalingGrade.A) },
        { ItemID.PirateStaff, new WeaponParams(2, 2, 0, 22, faiScalingGrade: ScalingGrade.B) },
        { ItemID.PlatinumAxe, new WeaponParams(5, 4) },
        { ItemID.PlatinumBow, new WeaponParams(4, 6, dexScalingGrade: ScalingGrade.E) },
        { ItemID.PlatinumBroadsword, new WeaponParams(8, 2, 0, 0, ScalingGrade.E) },
        { ItemID.PlatinumHammer, new WeaponParams(9, 2, 0, 0, ScalingGrade.D) },
        { ItemID.PlatinumPickaxe, new WeaponParams(3) },
        { ItemID.PlatinumShortsword, new WeaponParams(6, 2, 0, 0, ScalingGrade.E) },
        { ItemID.PoisonStaff, new WeaponParams(2, 2, 20, intScalingGrade: ScalingGrade.C) },
        { ItemID.PoisonedKnife, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.A) },
        { ItemID.PossessedHatchet, new WeaponParams(26, 5, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.ProximityMineLauncher, new WeaponParams(6, 24, dexScalingGrade: ScalingGrade.A) },
        { ItemID.PsychoKnife, new WeaponParams(22, 10, 0, 0, ScalingGrade.A, ScalingGrade.C) },
        { ItemID.PulseBow, new WeaponParams(4, 24, dexScalingGrade: ScalingGrade.B) },
        { ItemID.PurpleClubberfish, new WeaponParams(12, 5, 0, 0, ScalingGrade.A, ScalingGrade.D) },
        { ItemID.Pwnhammer, new WeaponParams(18, 2, 0, 0, ScalingGrade.B, ScalingGrade.E) },
        { ItemID.PygmyStaff, new WeaponParams(2, 2, 0, 26, faiScalingGrade: ScalingGrade.B) },
        { ItemID.QuadBarrelShotgun, new WeaponParams(3, 10, dexScalingGrade: ScalingGrade.C) },
        { ItemID.QueenSpiderStaff, new WeaponParams(1, 1, 0, 18, faiScalingGrade: ScalingGrade.D) },
        { ItemID.RainbowCrystalStaff, new WeaponParams(2, 2, 0, 46, faiScalingGrade: ScalingGrade.A) },
        { ItemID.RainbowGun, new WeaponParams(2, 2, 30, intScalingGrade: ScalingGrade.B) },
        { ItemID.RainbowRod, new WeaponParams(2, 2, 21, intScalingGrade: ScalingGrade.C) },
        { ItemID.Rally, new WeaponParams(6, 6, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.RavenStaff, new WeaponParams(2, 2, 0, 36, faiScalingGrade: ScalingGrade.A) },
        { ItemID.RazorbladeTyphoon, new WeaponParams(2, 2, 34, intScalingGrade: ScalingGrade.B) },
        { ItemID.Razorpine, new WeaponParams(2, 2, 32, intScalingGrade: ScalingGrade.B) },
        { ItemID.ReaverShark, new WeaponParams(10, 4, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.RedRyder, new WeaponParams(2, 12, dexScalingGrade: ScalingGrade.C) },
        { ItemID.RedsYoyo, new WeaponParams(15, 15, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.PrincessWeapon, new WeaponParams(2, 2, 30, intScalingGrade: ScalingGrade.B) },
        { ItemID.Revolver, new WeaponParams(2, 12, dexScalingGrade: ScalingGrade.C) },
        { ItemID.RichMahoganyBow, new WeaponParams() },
        { ItemID.RichMahoganyHammer, new WeaponParams() },
        { ItemID.RichMahoganySword, new WeaponParams() },
        { ItemID.RocketLauncher, new WeaponParams(6, 25, dexScalingGrade: ScalingGrade.A) },
        { ItemID.Rockfish, new WeaponParams(11, 4, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.RottenEgg, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.S) },
        { ItemID.RubyStaff, new WeaponParams(2, 2, 6, intScalingGrade: ScalingGrade.E) },
        { ItemID.Ruler, new WeaponParams(6, 4, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.SDMG, new WeaponParams(5, 45, dexScalingGrade: ScalingGrade.A) },
        { ItemID.Sandgun, new WeaponParams(2, 15, dexScalingGrade: ScalingGrade.D) },
        { ItemID.SanguineStaff, new WeaponParams(2, 2, 0, 17, faiScalingGrade: ScalingGrade.D) },
        { ItemID.SapphireStaff, new WeaponParams(2, 2, 6, intScalingGrade: ScalingGrade.E) },
        { ItemID.SawtoothShark, new WeaponParams(8, 4, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.ScarabBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.ScourgeoftheCorruptor, new WeaponParams(25, 8, 0, 0, ScalingGrade.B, ScalingGrade.C) },
        { ItemID.Seedler, new WeaponParams(24, 6, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.BouncingShield, new WeaponParams(12, 12, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.ShadewoodBow, new WeaponParams() },
        { ItemID.ShadewoodHammer, new WeaponParams() },
        { ItemID.ShadowJoustingLance, new WeaponParams(34, 6, 0, 0, ScalingGrade.S, ScalingGrade.D) },
        { ItemID.ShadowbeamStaff, new WeaponParams(2, 3, 28, intScalingGrade: ScalingGrade.B) },
        { ItemID.ShadowFlameBow, new WeaponParams(2, 18, dexScalingGrade: ScalingGrade.C) },
        { ItemID.ShadowFlameHexDoll, new WeaponParams(2, 1, 18, intScalingGrade: ScalingGrade.C) },
        { ItemID.ShadowFlameKnife, new WeaponParams(10, 8, 0, 0, ScalingGrade.C, ScalingGrade.C) },
        { ItemID.Shotgun, new WeaponParams(6, 12, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Shroomerang, new WeaponParams(6, 6, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.ShroomiteDiggingClaw, new WeaponParams(9) },
        { ItemID.Shuriken, new WeaponParams(2, 4, dexScalingGrade: ScalingGrade.B) },
        { ItemID.Sickle, new WeaponParams(4, 2, 0, 0, ScalingGrade.E) },
        { ItemID.SilverAxe, new WeaponParams(4, 2) },
        { ItemID.SilverBow, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.E) },
        { ItemID.SilverBroadsword, new WeaponParams(5, 2, 0, 0, ScalingGrade.E) },
        { ItemID.SilverHammer, new WeaponParams(6, 2, 0, 0, ScalingGrade.D) },
        { ItemID.SilverPickaxe, new WeaponParams(2) },
        { ItemID.SilverShortsword, new WeaponParams(4, 2, 0, 0, ScalingGrade.E) },
        { ItemID.MonkStaffT3, new WeaponParams(28, 8, 0, 0, ScalingGrade.B, ScalingGrade.C) },
        { ItemID.SkyFracture, new WeaponParams(2, 2, 20, intScalingGrade: ScalingGrade.C) },
        { ItemID.SlapHand, new WeaponParams(21, 5, 0, 0, ScalingGrade.S, ScalingGrade.D) },
        { ItemID.SlimeStaff, new WeaponParams(1, 1, 0, 7, faiScalingGrade: ScalingGrade.E) },
        { ItemID.ThornWhip, new WeaponParams(2, 2, 0, 10, faiScalingGrade: ScalingGrade.D) },
        { ItemID.SniperRifle, new WeaponParams(8, 30, dexScalingGrade: ScalingGrade.S) },
        { ItemID.Snowball, new WeaponParams(3, 3, 0, 0, ScalingGrade.B, ScalingGrade.B) },
        { ItemID.SnowballCannon, new WeaponParams(2, 8, dexScalingGrade: ScalingGrade.C) },
        { ItemID.SnowballLauncher, new WeaponParams() },
        { ItemID.SnowmanCannon, new WeaponParams(6, 30, dexScalingGrade: ScalingGrade.A) },
        { ItemID.SpaceGun, new WeaponParams(2, 2, 10, intScalingGrade: ScalingGrade.D) },
        { ItemID.Spear, new WeaponParams(3, 2) },
        { ItemID.SpectreHamaxe, new WeaponParams(27, 5, 0, 0, ScalingGrade.B, ScalingGrade.C) },
        { ItemID.SpectrePickaxe, new WeaponParams(9) },
        { ItemID.SpectreStaff, new WeaponParams(1, 1, 30, intScalingGrade: ScalingGrade.B) },
        { ItemID.SpiderStaff, new WeaponParams(2, 2, 0, 20, faiScalingGrade: ScalingGrade.C) },
        { ItemID.SpikyBall, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.BoneWhip, new WeaponParams(2, 2, 0, 12, faiScalingGrade: ScalingGrade.D) },
        { ItemID.SpiritFlame, new WeaponParams(2, 2, 18, intScalingGrade: ScalingGrade.C) },
        { ItemID.StaffofEarth, new WeaponParams(5, 2, 25, intScalingGrade: ScalingGrade.A) },
        { ItemID.StaffofRegrowth, new WeaponParams(3, 2, 1) },
        { ItemID.StaffoftheFrostHydra, new WeaponParams(2, 2, 0, 30, intScalingGrade: ScalingGrade.B) },
        { ItemID.StakeLauncher, new WeaponParams(5, 31, dexScalingGrade: ScalingGrade.A) },
        { ItemID.StarAnise, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.StarCannon, new WeaponParams(4, 14, dexScalingGrade: ScalingGrade.C) },
        { ItemID.StarWrath, new WeaponParams(40, 6, 4, 0, ScalingGrade.A, ScalingGrade.D, ScalingGrade.D, saturation: 60) },
        { ItemID.Starfury, new WeaponParams(9, 2, 4, 0, ScalingGrade.E, ScalingGrade.None, ScalingGrade.E) },
        { ItemID.PiercingStarlight, new WeaponParams(18, 20, 0, 0, ScalingGrade.C, ScalingGrade.A) },
        { ItemID.SparkleGuitar, new WeaponParams(3, 5, 32, intScalingGrade: ScalingGrade.B) },
        { ItemID.StickyBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.DirtStickyBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.StickyDynamite, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.StickyGrenade, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.ThunderSpear, new WeaponParams(6, 4, 0, 0, ScalingGrade.E) },
        { ItemID.StylistKilLaKillScissorsIWish, new WeaponParams(6, 4, 0, 0, ScalingGrade.E) },
        { ItemID.Stynger, new WeaponParams(5, 28, dexScalingGrade: ScalingGrade.A) },
        { ItemID.Sunfury, new WeaponParams(14, 5, 0, 0, ScalingGrade.B) },
        { ItemID.SuperStarCannon, new WeaponParams(5, 23, dexScalingGrade: ScalingGrade.B) },
        { ItemID.Swordfish, new WeaponParams(10, 5, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.TacticalShotgun, new WeaponParams(5, 28, dexScalingGrade: ScalingGrade.B) },
        { ItemID.TempestStaff, new WeaponParams(2, 2, 0, 30, faiScalingGrade: ScalingGrade.B) },
        { ItemID.TendonBow, new WeaponParams(2, 8, dexScalingGrade: ScalingGrade.E) },
        { ItemID.TentacleSpike, new WeaponParams(9, 4, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.TerraBlade, new WeaponParams(25, 6, 4, 0, ScalingGrade.B, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.Terragrim, new WeaponParams(5, 8, 0, 0, ScalingGrade.E, ScalingGrade.D) },
        { ItemID.EmpressBlade, new WeaponParams(2, 2, 0, 34, faiScalingGrade: ScalingGrade.A) },
        { ItemID.Terrarian, new WeaponParams(25, 25, 0, 0, ScalingGrade.A, ScalingGrade.A, saturation: 30) },
        { ItemID.TheAxe, new WeaponParams(20, 8, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.BeesKnees, new WeaponParams(2, 12, dexScalingGrade: ScalingGrade.D) },
        { ItemID.TheBreaker, new WeaponParams(12, 2, 0, 0, ScalingGrade.C) },
        { ItemID.TheEyeOfCthulhu, new WeaponParams(19, 19, 0, 0, ScalingGrade.A, ScalingGrade.A, saturation: 40) },
        { ItemID.TheHorsemansBlade, new WeaponParams(25, 8, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.TheMeatball, new WeaponParams(10, 5, 0, 0, ScalingGrade.D) },
        { ItemID.TheRottedFork, new WeaponParams(3, 8, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.TheUndertaker, new WeaponParams(2, 9, dexScalingGrade: ScalingGrade.D) },
        { ItemID.ThornChakram, new WeaponParams(7, 7, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.ThrowingKnife, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.ThunderStaff, new WeaponParams(2, 2, 7, intScalingGrade: ScalingGrade.D) },
        { ItemID.TinAxe, new WeaponParams() },
        { ItemID.TinBow, new WeaponParams() },
        { ItemID.TinBroadsword, new WeaponParams() },
        { ItemID.TinHammer, new WeaponParams() },
        { ItemID.TinPickaxe, new WeaponParams() },
        { ItemID.TinShortsword, new WeaponParams() },
        { ItemID.BookStaff, new WeaponParams(2, 2, 20, intScalingGrade: ScalingGrade.C) },
        { ItemID.TopazStaff, new WeaponParams(2, 2, 6, intScalingGrade: ScalingGrade.E) },
        { ItemID.ToxicFlask, new WeaponParams(2, 2, 28, intScalingGrade: ScalingGrade.A) },
        { ItemID.Toxikarp, new WeaponParams(2, 20, dexScalingGrade: ScalingGrade.D) },
        { ItemID.TragicUmbrella, new WeaponParams(6, 5, 0, 0, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.Trident, new WeaponParams(6, 4, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.Trimarang, new WeaponParams(6, 6, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.TrueExcalibur, new WeaponParams(21, 8, 0, 0, ScalingGrade.B, ScalingGrade.D) },
        { ItemID.TrueNightsEdge, new WeaponParams(20, 5, 4, 0, ScalingGrade.B, ScalingGrade.D, ScalingGrade.E) },
        { ItemID.Tsunami, new WeaponParams(4, 26, dexScalingGrade: ScalingGrade.B) },
        { ItemID.TungstenAxe, new WeaponParams(4, 2) },
        { ItemID.TungstenBow, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.E) },
        { ItemID.TungstenBroadsword, new WeaponParams(5, 2, 0, 0, ScalingGrade.E) },
        { ItemID.TungstenHammer, new WeaponParams(6, 2, 0, 0, ScalingGrade.D) },
        { ItemID.TungstenPickaxe, new WeaponParams(2) },
        { ItemID.TungstenShortsword, new WeaponParams(4, 2, 0, 0, ScalingGrade.E) },
        { ItemID.Umbrella, new WeaponParams(5, 4, 0, 0, ScalingGrade.E, ScalingGrade.E) },
        { ItemID.UnholyTrident, new WeaponParams(4, 2, 18, intScalingGrade: ScalingGrade.C) },
        { ItemID.UnholyWater, new WeaponParams() },
        { ItemID.Uzi, new WeaponParams(2, 18, dexScalingGrade: ScalingGrade.C) },
        { ItemID.ValkyrieYoyo, new WeaponParams(15, 15, 0, 0, ScalingGrade.C, ScalingGrade.C, saturation: 80) },
        { ItemID.Valor, new WeaponParams(8, 8, 0, 0, ScalingGrade.D, ScalingGrade.D) },
        { ItemID.VampireFrogStaff, new WeaponParams(1, 1, 10, faiScalingGrade: ScalingGrade.D) },
        { ItemID.VampireKnives, new WeaponParams(25, 10, 0, 0, ScalingGrade.A, ScalingGrade.D, saturation: 50) },
        { ItemID.VenomStaff, new WeaponParams(2, 2, 24, intScalingGrade: ScalingGrade.C) },
        { ItemID.VenusMagnum, new WeaponParams(2, 27, dexScalingGrade: ScalingGrade.C) },
        { ItemID.Vilethorn, new WeaponParams(1, 1, 8, intScalingGrade: ScalingGrade.E) },
        { ItemID.FieryGreatsword, new WeaponParams(12, 3, 0, 0, ScalingGrade.C, ScalingGrade.D) },
        { ItemID.WaffleIron, new WeaponParams(15, 10, 0, 0, ScalingGrade.S, ScalingGrade.D) },
        { ItemID.WandofFrosting, new WeaponParams() },
        { ItemID.WandofSparking, new WeaponParams(1, 1, 5) },
        { ItemID.WarAxeoftheNight, new WeaponParams(10, 2, 0, 0, ScalingGrade.E) },
        { ItemID.WaspGun, new WeaponParams(2, 2, 28, intScalingGrade: ScalingGrade.C) },
        { ItemID.WaterBolt, new WeaponParams(2, 2, 12, intScalingGrade: ScalingGrade.D) },
        { ItemID.WeatherPain, new WeaponParams(1, 1, 10, intScalingGrade: ScalingGrade.E) },
        { ItemID.WetBomb, new WeaponParams(2, 5, dexScalingGrade: ScalingGrade.B) },
        { ItemID.WoodenBoomerang, new WeaponParams() },
        { ItemID.WoodenBow, new WeaponParams() },
        { ItemID.WoodenHammer, new WeaponParams() },
        { ItemID.WoodenSword, new WeaponParams() },
        { ItemID.WoodYoyo, new WeaponParams() },
        { ItemID.XenoStaff, new WeaponParams(2, 2, 0, 30, faiScalingGrade: ScalingGrade.B) },
        { ItemID.Xenopopper, new WeaponParams(2, 30, dexScalingGrade: ScalingGrade.B) },
        { ItemID.Yelets, new WeaponParams(14, 14, 0, 0, ScalingGrade.C, ScalingGrade.C, saturation: 85) },
        { ItemID.Zenith, new WeaponParams(42, 10, 0, 0, ScalingGrade.A, ScalingGrade.C, saturation: 40) },
        { ItemID.ZombieArm, new WeaponParams(6, 4, 0, 0, ScalingGrade.E) }
    };
    
    
}
